### ISSUE TITLE
Example with React and ServerSide render 

### ISSUE THREAD

**Issue by OlegLustenko** [palmerhq/backpack#12]
I have tried to run backpack with koa2 and ServerSide-render and got an error about styles.

Here example: https://github.com/OlegLustenko/jyotish_gift

I'm using: "webpack-dev-middleware": "^1.8.4",
               "webpack-hot-middleware": "^2.13.2"
for client side

**Comment by jaredpalmer** [comment]
Although it's possible to use backpack for universal react apps, that is not the project's purpose. Furthermore, because of how Backpack currently reloads the server, you may have issues with things like HMR or react-hot-loader. Thus, I don't want to put examples showing Backpack + React yet. 

The goal of Backpack is to compliment tools like Create-React-App and Next.js. You should use 
those for your frontend application and then use Backpack to build your API. Your frontend and backend should be decoupled anyways. 

HOWEVER, there is a bunch of demand for a drop-in universal js build tool. See #13 for further discussion.

**Comment by jaredpalmer** [comment]
@OlegLustenko I believe the error you are running into can be solved as follows

```js
// backpack.config.js
const webpack = require('webpack)

module.exports = {
  weback: (config, options) => {
    // tell webpack to ignore any type of file ending with `.css`, `.less`, etc.
    config.plugins.push(new webpack.IgnorePlugin(/\.(css|less|img|svg)$/))
    return config
  }
}


```

**Comment by krainboltgreene** [comment]
What can I do to help make the react examples a reality? I'd love to replace an older webpack setup with this much simplified approach.

**Comment by jaredpalmer** [comment]
@krainboltgreene see #13 . Let's move this convo there.
