### ISSUE TITLE
RFC: Support for warn-require

### ISSUE THREAD

**Issue by amilajack** [palmerhq/backpack#30]
Would be nice if this project could feature something like HMR but for backend. `warm-require` is a module that makes this possible. Thoughts?

**Comment by ericclemmons** [comment]
This is how I do it:
https://github.com/ericclemmons/webpack-hot-server-example

Webpack supports HMR universally.

**Comment by wmertens** [comment]
And I'd like to add that it works quite well, but you have to write the
files to a build dir and you have to use the poll method. I haven't been
able to make the signal method work, and since the server runs in a
separate process, the files cannot be served from memoryfs.

(Kinda hoping that someone would make a webpack runner plugin that takes
care of both by patching require() so that it talks to webpack via a socket)

It is super nice to change your graphql resolvers and have them take hold
within a few seconds. Also, you can build a tree-shaken minimized version
of the server which starts very fast in production.

**Comment by jaredpalmer** [comment]
@wmertens would you be able to submit a POC PR for this>

**Comment by wmertens** [comment]
Sorry I don't use backpack myself but I can certainly give hints…
