### ISSUE TITLE
Nodemon auto reload doesn't work if entry file is not in 'src' folder

### ISSUE THREAD

**Issue by Vija02** [palmerhq/backpack#35]
As the title say, if the entry file is in another location, for example: 

backpack.config.js
```
module.exports = {
  webpack: (config) => {
    // Change entry file
    config.entry.main = [
      './test/app.js'
    ];
    return config;
  }
}
```

```
backpack dev
```
Won't reload the file when changed

**Comment by Vija02** [comment]
If I change the value of serverSrcPath in /config/paths.js, it will work.
```
serverSrcPath: path.join(rootPath, 'src'),
```
to
```
serverSrcPath: path.join(rootPath, 'test'),
```

**Comment by jaredpalmer** [comment]
I think the issue is actually that chokidar is watching [`path.serverSrcPath`](https://github.com/palmerhq/backpack/blob/master/packages/backpack-core/bin/dev#L43) which is not configurable. I think it should instead watch for [`serverPaths`](https://github.com/palmerhq/backpack/blob/master/packages/backpack-core/bin/dev#L32) which walks the `webpack.config.entry`.
